FROM node:22-alpine AS base
RUN npm install -g pnpm
ENV CI=true

FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build --filter=@mifal-israel/bot...

FROM base AS runner
WORKDIR /app
COPY --from=builder /app /app
WORKDIR /app/apps/bot
CMD ["pnpm", "start"]
