FROM node:22-alpine AS base
RUN npm install -g pnpm
RUN apk add --no-cache openssl
RUN apk add --no-cache libssl1.1 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.15/main
ENV CI=true

FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build --filter=@mifal-israel/backend...

FROM base AS runner
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000
WORKDIR /app/apps/backend
CMD ["pnpm", "start"]
